"""Persuasion strategy and campaign plan data models.

This module defines the output data structures for persuasion
strategy recommendations generated by the system.
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from src.nudge.analyzer import AttackStrategy, ChoiceArchitectureTechnique, NudgeOpportunity
from src.nudge.interventions import Intervention, InterventionPlan

logger = logging.getLogger(__name__)


@dataclass
class TargetProfile:
    """Profile of a persuasion target."""

    agent_name: str
    interest_group: str
    political_alignment: str
    flexibility: float
    key_values: list[str] = field(default_factory=list)
    red_lines: list[str] = field(default_factory=list)
    vulnerability_areas: list[str] = field(default_factory=list)
    recommended_approach: str = ""
    compatibility_with_others: dict[str, float] = field(default_factory=dict)


@dataclass
class PersuasionStrategy:
    """A complete persuasion strategy for a debate scenario.

    This is the main output structure containing all analysis results
    and recommendations.
    """

    id: UUID = field(default_factory=uuid4)
    name: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    topic: str = ""
    goal: str = ""

    # Target profiles
    target_profiles: list[TargetProfile] = field(default_factory=list)

    # Debate analysis
    common_ground_identified: list[str] = field(default_factory=list)
    key_disputes: list[str] = field(default_factory=list)
    position_shifts_observed: list[str] = field(default_factory=list)

    # Opportunities and interventions
    top_opportunities: list[NudgeOpportunity] = field(default_factory=list)
    recommended_interventions: list[Intervention] = field(default_factory=list)

    # Strategy summary
    primary_strategy: AttackStrategy = AttackStrategy.VALUE_ALIGNMENT
    primary_technique: ChoiceArchitectureTechnique = ChoiceArchitectureTechnique.FRAMING
    strategy_rationale: str = ""

    # Coalition recommendations
    coalition_opportunities: list[str] = field(default_factory=list)
    sequencing_notes: str = ""

    # Success metrics
    estimated_overall_effectiveness: float = 0.5
    key_success_indicators: list[str] = field(default_factory=list)
    risk_factors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "id": str(self.id),
            "name": self.name,
            "created_at": self.created_at.isoformat(),
            "topic": self.topic,
            "goal": self.goal,
            "target_profiles": [
                {
                    "agent_name": tp.agent_name,
                    "interest_group": tp.interest_group,
                    "political_alignment": tp.political_alignment,
                    "flexibility": tp.flexibility,
                    "key_values": tp.key_values,
                    "red_lines": tp.red_lines,
                    "vulnerability_areas": tp.vulnerability_areas,
                    "recommended_approach": tp.recommended_approach,
                }
                for tp in self.target_profiles
            ],
            "common_ground": self.common_ground_identified,
            "key_disputes": self.key_disputes,
            "position_shifts": self.position_shifts_observed,
            "top_opportunities": [
                {
                    "target": o.target_agent,
                    "topic": o.topic,
                    "strategy": o.strategy_type.value,
                    "technique": o.technique.value,
                    "effectiveness": o.estimated_effectiveness,
                    "suggested_message": o.suggested_message,
                }
                for o in self.top_opportunities
            ],
            "recommended_interventions": [
                {
                    "name": i.name,
                    "target": i.target_agent,
                    "topic": i.target_topic,
                    "primary_message": i.primary_message,
                    "supporting_points": i.supporting_points,
                    "timing": i.timing_recommendation,
                    "effectiveness": i.estimated_effectiveness,
                }
                for i in self.recommended_interventions
            ],
            "primary_strategy": self.primary_strategy.value,
            "primary_technique": self.primary_technique.value,
            "strategy_rationale": self.strategy_rationale,
            "coalition_opportunities": self.coalition_opportunities,
            "sequencing_notes": self.sequencing_notes,
            "estimated_effectiveness": self.estimated_overall_effectiveness,
            "success_indicators": self.key_success_indicators,
            "risk_factors": self.risk_factors,
        }

    def to_json(self, indent: int = 2) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def summary(self) -> str:
        """Generate human-readable summary."""
        lines = [
            f"PERSUASION STRATEGY: {self.name}",
            f"Topic: {self.topic}",
            f"Goal: {self.goal}",
            "",
            f"Primary Approach: {self.primary_strategy.value} with {self.primary_technique.value}",
            f"Estimated Effectiveness: {self.estimated_overall_effectiveness:.0%}",
            "",
            f"TARGET PROFILES ({len(self.target_profiles)}):",
        ]

        for tp in self.target_profiles:
            lines.append(f"  - {tp.agent_name} ({tp.interest_group})")
            lines.append(f"    Approach: {tp.recommended_approach}")

        lines.extend(
            [
                "",
                f"COMMON GROUND ({len(self.common_ground_identified)}):",
            ]
        )
        for cg in self.common_ground_identified[:3]:
            lines.append(f"  - {cg}")

        lines.extend(
            [
                "",
                f"TOP OPPORTUNITIES ({len(self.top_opportunities)}):",
            ]
        )
        for opp in self.top_opportunities[:3]:
            lines.append(
                f"  - {opp.target_agent}: {opp.topic[:40]} ({opp.estimated_effectiveness:.0%})"
            )

        lines.extend(
            [
                "",
                f"KEY RISKS ({len(self.risk_factors)}):",
            ]
        )
        for risk in self.risk_factors[:3]:
            lines.append(f"  - {risk}")

        return "\n".join(lines)


@dataclass
class CampaignPlan:
    """A multi-phase campaign plan for sustained persuasion efforts.

    This extends the basic strategy with phased execution planning
    for longer-term persuasion campaigns.
    """

    id: UUID = field(default_factory=uuid4)
    name: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    overall_goal: str = ""

    # Base strategy
    base_strategy: Optional[PersuasionStrategy] = None

    # Phases
    phases: list[dict] = field(default_factory=list)

    # Metrics and tracking
    milestone_definitions: list[str] = field(default_factory=list)
    success_criteria: list[str] = field(default_factory=list)
    measurement_approach: str = ""

    # Contingencies
    contingency_plans: dict[str, str] = field(default_factory=dict)

    def add_phase(
        self,
        name: str,
        goal: str,
        interventions: list[Intervention],
        duration_note: str = "",
        dependencies: list[str] = None,
    ) -> None:
        """Add a phase to the campaign plan.

        Args:
            name: Phase name
            goal: Phase goal
            interventions: Interventions for this phase
            duration_note: Note about phase duration
            dependencies: Phases this depends on
        """
        phase = {
            "name": name,
            "goal": goal,
            "interventions": [
                {
                    "target": i.target_agent,
                    "topic": i.target_topic,
                    "message": i.primary_message[:200],
                }
                for i in interventions
            ],
            "duration_note": duration_note,
            "dependencies": dependencies or [],
        }
        self.phases.append(phase)
        logger.debug(f"Added phase '{name}' with {len(interventions)} interventions")

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        result = {
            "id": str(self.id),
            "name": self.name,
            "created_at": self.created_at.isoformat(),
            "overall_goal": self.overall_goal,
            "phases": self.phases,
            "milestones": self.milestone_definitions,
            "success_criteria": self.success_criteria,
            "measurement_approach": self.measurement_approach,
            "contingencies": self.contingency_plans,
        }

        if self.base_strategy:
            result["base_strategy_id"] = str(self.base_strategy.id)
            result["base_strategy_name"] = self.base_strategy.name

        return result

    def to_json(self, indent: int = 2) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def summary(self) -> str:
        """Generate human-readable summary."""
        lines = [
            f"CAMPAIGN PLAN: {self.name}",
            f"Goal: {self.overall_goal}",
            "",
            f"PHASES ({len(self.phases)}):",
        ]

        for i, phase in enumerate(self.phases, 1):
            lines.append(f"  Phase {i}: {phase['name']}")
            lines.append(f"    Goal: {phase['goal']}")
            lines.append(f"    Interventions: {len(phase['interventions'])}")
            if phase.get("duration_note"):
                lines.append(f"    Duration: {phase['duration_note']}")

        lines.extend(
            [
                "",
                "SUCCESS CRITERIA:",
            ]
        )
        for criterion in self.success_criteria[:3]:
            lines.append(f"  - {criterion}")

        return "\n".join(lines)


@dataclass
class DebateReport:
    """Complete report of a debate simulation including strategy."""

    id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=datetime.utcnow)
    topic: str = ""
    participants: list[str] = field(default_factory=list)

    # Debate results
    total_rounds: int = 0
    total_messages: int = 0
    transcript_summary: str = ""

    # Analysis results
    common_ground: list[str] = field(default_factory=list)
    remaining_disputes: list[str] = field(default_factory=list)
    position_shifts: list[dict] = field(default_factory=list)

    # Strategy recommendation
    persuasion_strategy: Optional[PersuasionStrategy] = None

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        result = {
            "id": str(self.id),
            "created_at": self.created_at.isoformat(),
            "topic": self.topic,
            "participants": self.participants,
            "total_rounds": self.total_rounds,
            "total_messages": self.total_messages,
            "transcript_summary": self.transcript_summary,
            "common_ground": self.common_ground,
            "remaining_disputes": self.remaining_disputes,
            "position_shifts": self.position_shifts,
        }

        if self.persuasion_strategy:
            result["persuasion_strategy"] = self.persuasion_strategy.to_dict()

        return result

    def to_json(self, indent: int = 2) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)
